export enum ProductType {
  CUENTA_AHORROS = 'CUENTA_AHORROS',
  CUENTA_CORRIENTE = 'CUENTA_CORRIENTE',
  CREDITO_PERSONAL = 'CREDITO_PERSONAL',
  TARJETA_CREDITO_AMEX = 'TARJETA_CREDITO_AMEX',
  TARJETA_CREDITO_VISA = 'TARJETA_CREDITO_VISA',
  TARJETA_CREDITO_MASTER_CARD = 'TARJETA_CREDITO_MASTER_CARD',
}
