
server:
  port: 8080
spring:
  application:
    name: ms-config-server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/bzavalavaldivia/ibk-challenge
          search-paths: config-data